// このファイルは機械的に出力されました。

export const NAME_DICT: { en: string; ja: string }[] = [
  { en: "Mek", ja: "MEK" },
  { en: "R-Allosaurus", ja: "Rアロサウルス" },
  { en: "R-Equus", ja: "Rエクウス" },
  { en: "R-Gasbags", ja: "Rガスバッグ" },
  { en: "R-Carnotaurus", ja: "Rカルノタウルス" },
  { en: "R-Carbonemys", ja: "Rカルボネミス" },
  { en: "R-Giganotosaurus", ja: "Rギガノトサウルス" },
  { en: "R-Quetzal", ja: "Rケツァルコアトルス" },
  { en: "R-Dire Bear", ja: "Rショートフェイスベア" },
  { en: "R-Direwolf", ja: "Rダイアウルフ" },
  { en: "R-Daeodon", ja: "Rダエオドン" },
  { en: "R-Thylacoleo", ja: "Rティラコレオ" },
  { en: "R-Dilophosaur", ja: "Rディロフォサウルス" },
  { en: "R-Parasaur", ja: "Rパラサウロロフス" },
  { en: "R-Procoptodon", ja: "Rプロコプトドン" },
  { en: "R-Brontosaurus", ja: "Rブロントサウルス" },
  { en: "R-Velonasaur", ja: "Rベロナサウルス" },
  { en: "R-Megatherium", ja: "Rメガテリウム" },
  { en: "R-Reaper King", ja: "Rリーパーキング" },
  { en: "R-Reaper Queen", ja: "Rリーパークイーン" },
  { en: "R-Snow Owl", ja: "R雪フクロウ" },
  { en: "Tek Giganotosaurus", ja: "TEKギガノトサウルス" },
  { en: "Tek Quetzal", ja: "TEKケツァルコアトルス" },
  { en: "Tek Stegosaurus", ja: "TEKステゴサウルス" },
  { en: "Tek Stryder", ja: "TEKストライダー" },
  { en: "Tek Rex", ja: "TEKティラノサウルス" },
  { en: "Tek Triceratops", ja: "TEKトリケラトプス" },
  { en: "Tek Parasaur", ja: "TEKパラサウロロフス" },
  { en: "Tek Raptor", ja: "TEKユタラプトル" },
  { en: "VR Astrodelphis", ja: "VRアストロデルフィス" },
  { en: "VR Araneo", ja: "VRアラネオモーフス" },
  { en: "VR Argentavis", ja: "VRアルゲンタヴィス" },
  { en: "VR Allosaurus", ja: "VRアロサウルス" },
  { en: "VR Enforcer", ja: "VRエンフォーサー" },
  { en: "VR Onyc", ja: "VRオニコニクテリス" },
  { en: "VR Kaprosuchus", ja: "VRカプロスクス" },
  { en: "VR Mantis", ja: "VRカマキリ" },
  { en: "VR Chalicotherium", ja: "VRカリコテリウム" },
  { en: "VR Karkinos", ja: "VRカルキノス" },
  { en: "VR Carnotaurus", ja: "VRカルノタウルス" },
  { en: "VR Shadowmane", ja: "VRシャドウメイン" },
  { en: "VR Stegosaurus", ja: "VRステゴサウルス" },
  { en: "VR Tapejara", ja: "VRタペヤラ" },
  { en: "VR Titanoboa", ja: "VRティタノボア" },
  { en: "VR Dimorphodon", ja: "VRディモルフォドン" },
  { en: "VR Rex", ja: "VRティラノサウルス" },
  { en: "VR Dilophosaur", ja: "VRディロフォサウルス" },
  { en: "VR Terror Bird", ja: "VRテラーバード" },
  { en: "VR Triceratops", ja: "VRトリケラトプス" },
  { en: "VR Pachy", ja: "VRパキケファロサウルス" },
  { en: "VR Parasaur", ja: "VRパラサウロロフス" },
  { en: "VR Ferox", ja: "VRフェロクス" },
  { en: "VR Bloodstalker", ja: "VRブラッドストーカー" },
  { en: "VR Pulmonoscorpius", ja: "VRプルモノスコルピウス" },
  { en: "VR Velonasaur", ja: "VRベロナサウルス" },
  { en: "VR Megatherium", ja: "VRメガテリウム" },
  { en: "VR Megalania", ja: "VRメガラニア" },
  { en: "VR Raptor", ja: "VRユタラプトル" },
  { en: "VR Ravager", ja: "VRラベジャー" },
  { en: "VR Lymantria", ja: "VRリマントリア" },
  { en: "X-Argentavis", ja: "Xアルゲンタヴィス" },
  { en: "X-Allosaurus", ja: "Xアロサウルス" },
  { en: "X-Ankylosaurus", ja: "Xアンキロサウルス" },
  { en: "X-Ichthyosaurus", ja: "Xイクチオサウルス" },
  { en: "X-Otter", ja: "Xカワウソ" },
  { en: "X-Woolly Rhino", ja: "Xケブカサイ" },
  { en: "X-Sabertooth", ja: "Xサーベルタイガー" },
  { en: "X-Spino", ja: "Xスピノサウルス" },
  { en: "X-Sabertooth Salmon", ja: "Xセイバートゥース・サーモン" },
  { en: "X-Tapejara", ja: "Xタペヤラ" },
  { en: "X-Dunkleosteus", ja: "Xダンクルオステウス" },
  { en: "X-Rex", ja: "Xティラノサウルス" },
  { en: "X-Triceratops", ja: "Xトリケラトプス" },
  { en: "X-Basilosaurus", ja: "Xバシロサウルス" },
  { en: "X-Paraceratherium", ja: "Xパラケラテリウム" },
  { en: "X-Parasaur", ja: "Xパラサウロロフス" },
  { en: "X-Megalodon", ja: "Xメガロドン" },
  { en: "X-Mosasaurus", ja: "Xモササウルス" },
  { en: "X-Yutyrannus", ja: "Xユウティラヌス" },
  { en: "X-Raptor", ja: "Xユタラプトル" },
  { en: "X-Rock Elemental", ja: "Xロックエレメンタル" },
  { en: "Arthropluera", ja: "アースロプレウラ" },
  { en: "Aberrant Arthropluera", ja: "アースロプレウラ変種" },
  { en: "Ice Titan", ja: "アイス・タイタン" },
  { en: "Ice Golem", ja: "アイスエレメンタル" },
  { en: "Iceworm Male", ja: "アイスワーム(オス)" },
  { en: "Iceworm Queen", ja: "アイスワーム(女王)" },
  { en: "Ice Wyvern", ja: "アイスワイバーン" },
  { en: "Astrocetus", ja: "アストロセタス" },
  { en: "Astrodelphis", ja: "アストロデルフィス" },
  { en: "Attack Drone", ja: "アタックドローン" },
  { en: "Achatina", ja: "アフリカマイマイ" },
  { en: "Aberrant Achatina", ja: "アフリカマイマイ変種" },
  { en: "Amargasaurus", ja: "アマルガサウルス" },
  { en: "Araneo", ja: "アラネオモーフス" },
  { en: "Aberrant Araneo", ja: "アラネオモーフス変種" },
  { en: "Argentavis", ja: "アルゲンタヴィス" },
  { en: "Alpha X-Triceratops", ja: "アルファ・Xトリケラトプス" },
  { en: "Alpha Karkinos", ja: "アルファ・カルキノス" },
  { en: "Alpha Carnotaurus", ja: "アルファ・カルノタウルス" },
  { en: "Alpha King Titan", ja: "アルファ・コロッサル・タイタン" },
  {
    en: "Alpha Surface Reaper King",
    ja: "アルファ・サーフェス・リーパーキング",
  },
  { en: "Alpha Deathworm", ja: "アルファ・デスワーム" },
  { en: "Alpha Tusoteuthis", ja: "アルファ・トゥソテウティス" },
  { en: "Alpha Basilisk", ja: "アルファ・バジリスク" },
  { en: "Alpha Fire Wyvern", ja: "アルファ・ファイアワイバーン" },
  {
    en: "Alpha Blood Crystal Wyvern",
    ja: "アルファ・ブラッド・クリスタルワイバーン",
  },
  { en: "Alpha Megalodon", ja: "アルファ・メガロドン" },
  { en: "Alpha Mosasaur", ja: "アルファ・モササウルス" },
  { en: "Alpha Raptor", ja: "アルファ・ラプトル" },
  { en: "Alpha Leedsichthys", ja: "アルファ・リードシクティス" },
  { en: "Alpha T-Rex", ja: "アルファ・レックス" },
  { en: "Allosaurus", ja: "アロサウルス" },
  { en: "Ankylosaurus", ja: "アンキロサウルス" },
  { en: "Aberrant Ankylosaurus", ja: "アンキロサウルス変種" },
  { en: "Anglerfish", ja: "アンコウ" },
  { en: "Aberrant Anglerfish", ja: "アンコウ変種" },
  { en: "Andrewsarchus", ja: "アンドリューサルクス" },
  { en: "Ammonite", ja: "アンモナイト" },
  { en: "Yeti", ja: "イエティ" },
  { en: "Iguanodon", ja: "イグアノドン" },
  { en: "Aberrant Iguanodon", ja: "イグアノドン変種" },
  { en: "Ichthyosaurus", ja: "イクチオサウルス" },
  { en: "Ichthyornis", ja: "イクチオルニス" },
  { en: "Voidwyrm", ja: "ヴォイドワーム" },
  { en: "Eurypterid", ja: "ウミサソリ" },
  { en: "Equus", ja: "エクウス" },
  { en: "Aberrant Equus", ja: "エクウス変種" },
  { en: "Exo-Mek", ja: "エクソMEK" },
  { en: "Malfunctioned Mek Knight", ja: "エラーを起こしたMEKナイト" },
  {
    en: "Malfunctioned Tek Giganotosaurus",
    ja: "エラーを起こしたTEKギガノトサウルス",
  },
  {
    en: "Malfunctioned Tek Quetzal",
    ja: "エラーを起こしたTEKケツァルコアトルス",
  },
  {
    en: "Malfunctioned Tek Stegosaurus",
    ja: "エラーを起こしたTEKステゴサウルス",
  },
  { en: "Malfunctioned Tek Stryder", ja: "エラーを起こしたTEKストライダー" },
  { en: "Malfunctioned Tek Rex", ja: "エラーを起こしたTEKティラノサウルス" },
  {
    en: "Malfunctioned Tek Triceratops",
    ja: "エラーを起こしたTEKトリケラトプス",
  },
  {
    en: "Malfunctioned Tek Parasaur",
    ja: "エラーを起こしたTEKパラサウロロフス",
  },
  { en: "Malfunctioned Tek Raptor", ja: "エラーを起こしたTEKユタラプトル" },
  { en: "Malfunctioned Attack Drone", ja: "エラーを起こしたアタックドローン" },
  { en: "Malfunctioned Enforcer", ja: "エラーを起こしたエンフォーサー" },
  {
    en: "Brute Malfunctioned Tek Giganotosaurus",
    ja: "エラーを起こした凶暴なTEKギガノトサウルス",
  },
  {
    en: "Brute Malfunctioned Tek Rex",
    ja: "エラーを起こした凶暴なTEKティラノサウルス",
  },
  { en: "Malfunctioned Defense Unit", ja: "エラーを起こした防御ユニット" },
  { en: "Elemental Reaper King", ja: "エレメンタル・リーパーキング" },
  { en: "Ember Crystal Wyvern", ja: "エンバー・クリスタルワイバーン" },
  { en: "Enforcer", ja: "エンフォーサー" },
  { en: "Oviraptor", ja: "オヴィラプトル" },
  { en: "Onyc", ja: "オニコニクテリス" },
  { en: "Kairuku", ja: "カイルクペンギン" },
  { en: "Castoroides", ja: "カストロイデス" },
  { en: "Gasbags", ja: "ガスバッグ" },
  { en: "Gacha", ja: "ガチャ" },
  { en: "GachaClaus", ja: "ガチャクロース" },
  { en: "Kaprosuchus", ja: "カプロスクス" },
  { en: "Mantis", ja: "カマキリ" },
  { en: "Chalicotherium", ja: "カリコテリウム" },
  { en: "Gallimimus", ja: "ガリミムス" },
  { en: "Carcharodontosaurus", ja: "カルカロドントサウルス" },
  { en: "Karkinos", ja: "カルキノス" },
  { en: "Carnotaurus", ja: "カルノタウルス" },
  { en: "Aberrant Carnotaurus", ja: "カルノタウルス変種" },
  { en: "Carbonemys", ja: "カルボネミス" },
  { en: "Aberrant Carbonemys", ja: "カルボネミス変種" },
  { en: "Otter", ja: "カワウソ" },
  { en: "Aberrant Otter", ja: "カワウソ変種" },
  { en: "Gamma King Titan", ja: "ガンマ・コロッサル・タイタン" },
  { en: "Giganotosaurus", ja: "ギガノトサウルス" },
  { en: "Gigantopithecus", ja: "ギガントピテクス" },
  { en: "Aberrant Gigantopithecus", ja: "ギガントピテクス変種" },
  { en: "Cnidaria", ja: "クニダリア" },
  { en: "Aberrant Cnidaria", ja: "クニダリア変種" },
  { en: "Griffin", ja: "グリフィン" },
  { en: "Glowtail", ja: "グローテール" },
  { en: "Glowbug", ja: "グローバグ" },
  { en: "Quetzal", ja: "ケツァルコアトルス" },
  { en: "Woolly Rhino", ja: "ケブカサイ" },
  { en: "Kentrosaurus", ja: "ケントロサウルス" },
  { en: "Mantis Ghost", ja: "ゴーストカマキリ" },
  { en: "Surface Reaper King Ghost", ja: "ゴーストサーフェス・リーパーキング" },
  { en: "Direwolf Ghost", ja: "ゴーストダイアウルフ" },
  { en: "Rex Ghost", ja: "ゴーストティラノサウルス" },
  { en: "Basilisk Ghost", ja: "ゴーストバジリスク" },
  { en: "Bulbdog Ghost", ja: "ゴーストバルブドッグ" },
  { en: "Snow Owl Ghost", ja: "ゴースト雪フクロウ" },
  { en: "King Titan", ja: "コロッサル・タイタン" },
  { en: "Compy", ja: "コンプソグナトゥス" },
  { en: "Surface Reaper King", ja: "サーフェス・リーパーキング" },
  { en: "Sabertooth", ja: "サーベルタイガー" },
  { en: "Aberrant Salmon", ja: "サーモン変種" },
  { en: "Subterranean Reaper King", ja: "サブテラニアン・リーパーキング" },
  { en: "Summoner", ja: "サモナー" },
  { en: "Sarco", ja: "サルコスクス" },
  { en: "Aberrant Sarco", ja: "サルコスクス変種" },
  { en: "Seeker", ja: "シーカー" },
  { en: "Coelacanth", ja: "シーラカンス" },
  { en: "Aberrant Coelacanth", ja: "シーラカンス変種" },
  { en: "Sinomacrops", ja: "シノマクロプス" },
  { en: "Shinehorn", ja: "シャインホーン" },
  { en: "Oil Jug Bug", ja: "ジャグ・バグ(原油)" },
  { en: "Shadowmane", ja: "シャドウメイン" },
  { en: "Dire Bear", ja: "ショートフェイスベア" },
  { en: "Aberrant Dire Bear", ja: "ショートフェイスベア変種" },
  { en: "Super Turkey", ja: "スーパー七面鳥" },
  { en: "Scout", ja: "スカウト" },
  { en: "Skeletal Carnotaurus", ja: "スケルタル・カルノタウルス" },
  { en: "Skeletal Giganotosaurus", ja: "スケルタル・ギガノトサウルス" },
  { en: "Skeletal Quetzal", ja: "スケルタル・ケツァルコアトルス" },
  { en: "Skeletal Stego", ja: "スケルタル・ステゴサウルス" },
  { en: "Skeletal Rex", ja: "スケルタル・ティラノサウルス" },
  { en: "Skeletal Jerboa", ja: "スケルタル・トビネズミ" },
  { en: "Skeletal Trike", ja: "スケルタル・トリケラトプス" },
  { en: "Skeletal Bronto", ja: "スケルタル・ブロントサウルス" },
  { en: "Skeletal Raptor", ja: "スケルタル・ユタラプトル" },
  { en: "Sköll", ja: "スコル" },
  { en: "Steinbjörn", ja: "スタインヨルン" },
  { en: "Stegosaurus", ja: "ステゴサウルス" },
  { en: "Aberrant Stegosaurus", ja: "ステゴサウルス変種" },
  { en: "Spino", ja: "スピノサウルス" },
  { en: "Aberrant Spino", ja: "スピノサウルス変種" },
  { en: "Sabertooth Salmon", ja: "セイバートゥース・サーモン" },
  { en: "Zomdodo", ja: "ゾンビドードー" },
  { en: "Zombie Fire Wyvern", ja: "ゾンビファイアワイバーン" },
  { en: "Zombie Poison Wyvern", ja: "ゾンビポイズンワイバーン" },
  { en: "Zombie Lightning Wyvern", ja: "ゾンビライトニングワイバーン" },
  { en: "Direwolf", ja: "ダイアウルフ" },
  { en: "Dire Polar Bear", ja: "ダイアホッキョクグマ" },
  { en: "Daeodon", ja: "ダエオドン" },
  { en: "Tapejara", ja: "タペヤラ" },
  { en: "Dunkleosteus", ja: "ダンクルオステウス" },
  { en: "Chalk Golem", ja: "チョークエレメンタル" },
  { en: "Titanosaur", ja: "ティタノサウルス" },
  { en: "Titanoboa", ja: "ティタノボア" },
  { en: "Aberrant Titanoboa", ja: "ティタノボア変種" },
  { en: "Titanomyrma Soldier", ja: "ティタノミルマ・ソルジャー" },
  { en: "Titanomyrma Drone", ja: "ティタノミルマ・ドローン" },
  { en: "Deinonychus", ja: "デイノニクス" },
  { en: "Dinopithecus", ja: "ディノピテクス" },
  { en: "Dinopithecus King", ja: "ディノピテクスキング" },
  { en: "Diplocaulus", ja: "ディプロカウルス" },
  { en: "Aberrant Diplocaulus", ja: "ディプロカウルス変種" },
  { en: "Diplodocus", ja: "ディプロドクス" },
  { en: "Aberrant Diplodocus", ja: "ディプロドクス変種" },
  { en: "Dimetrodon", ja: "ディメトロドン" },
  { en: "Aberrant Dimetrodon", ja: "ディメトロドン変種" },
  { en: "Dimorphodon", ja: "ディモルフォドン" },
  { en: "Aberrant Dimorphodon", ja: "ディモルフォドン変種" },
  { en: "Thylacoleo", ja: "ティラコレオ" },
  { en: "Rex", ja: "ティラノサウルス" },
  { en: "Dilophosaur", ja: "ディロフォサウルス" },
  { en: "Desert Titan", ja: "デザート・タイタン" },
  { en: "Desert Titan Flock", ja: "デザート・タイタンの群れ" },
  { en: "Desmodus", ja: "デスモダス" },
  { en: "Deathworm", ja: "デスワーム" },
  { en: "Terror Bird", ja: "テラーバード" },
  { en: "Therizinosaur", ja: "テリジノサウルス" },
  { en: "Electrophorus", ja: "デンキウナギ" },
  { en: "Aberrant Electrophorus", ja: "デンキウナギ変種" },
  { en: "Dodo", ja: "ドードー" },
  { en: "DodoRex", ja: "ドードーレックス" },
  { en: "Dodo Wyvern", ja: "ドードーワイバーン" },
  { en: "Aberrant Dodo", ja: "ドードー変種" },
  { en: "Tusoteuthis", ja: "トゥソテウティス" },
  { en: "Doedicurus", ja: "ドエディクルス" },
  { en: "Aberrant Doedicurus", ja: "ドエディクルス変種" },
  { en: "Jerboa", ja: "トビネズミ" },
  { en: "Dragon", ja: "ドラゴン" },
  { en: "Triceratops", ja: "トリケラトプス" },
  { en: "Aberrant Triceratops", ja: "トリケラトプス変種" },
  { en: "Troodon", ja: "トロオドン" },
  { en: "Tropical Crystal Wyvern", ja: "トロピカル・クリスタルワイバーン" },
  { en: "Tropeognathus", ja: "トロペオグナトゥス" },
  { en: "Nameless", ja: "ネームレス" },
  { en: "Noglin", ja: "ノグリン" },
  { en: "Party Dodo", ja: "パーティードードー" },
  { en: "Pachy", ja: "パキケファロサウルス" },
  { en: "Pachyrhinosaurus", ja: "パキリノサウルス" },
  { en: "Vulture", ja: "ハゲワシ" },
  { en: "Basilisk", ja: "バジリスク" },
  { en: "Basilosaurus", ja: "バシロサウルス" },
  { en: "Hati", ja: "ハティ" },
  { en: "Bunny Oviraptor", ja: "バニーオヴィラプトル" },
  { en: "Bunny Dodo", ja: "バニードードー" },
  { en: "Parakeet Fish School", ja: "パラキートの魚群" },
  { en: "Paraceratherium", ja: "パラケラテリウム" },
  { en: "Aberrant Paraceratherium", ja: "パラケラテリウム変種" },
  { en: "Parasaur", ja: "パラサウロロフス" },
  { en: "Aberrant Parasaur", ja: "パラサウロロフス変種" },
  { en: "Baryonyx", ja: "バリオニクス" },
  { en: "Aberrant Baryonyx", ja: "バリオニクス変種" },
  { en: "Bulbdog", ja: "バルブドッグ" },
  { en: "Hyaenodon", ja: "ヒエノドン" },
  { en: "Ovis", ja: "ヒツジ" },
  { en: "Aberrant Ovis", ja: "ヒツジ変種" },
  { en: "Leech", ja: "ヒル" },
  { en: "Fire Wyvern", ja: "ファイアワイバーン" },
  { en: "Water Jug Bug", ja: "ファイル:ジャグバグ(水).png ジャグバグ(水)" },
  {
    en: "Bone Fire Wyvern",
    ja: "ファイル:スケルタル・ファイアワイバーン.png スケルタル・ファイアワイバーン",
  },
  { en: "Phiomia", ja: "フィオミア" },
  { en: "Fjordhawk", ja: "フィヨルドホーク" },
  { en: "Featherlight", ja: "フェザーライト" },
  { en: "Phoenix", ja: "フェニックス" },
  { en: "Ferox", ja: "フェロクス" },
  { en: "Fenrir", ja: "フェンリル" },
  { en: "Fenrisúlfr", ja: "フェンリル (ボス)" },
  { en: "Forest Titan", ja: "フォレスト・タイタン" },
  { en: "Forest Wyvern", ja: "フォレストワイバーン" },
  { en: "Pteranodon", ja: "プテラノドン" },
  { en: "Blood Crystal Wyvern", ja: "ブラッド・クリスタルワイバーン" },
  { en: "Bloodstalker", ja: "ブラッドストーカー" },
  { en: "Broodmother Lysrix", ja: "ブルードマザー" },
  { en: "Scorpion", ja: "プルモノスコルピウス" },
  { en: "Aberrant Pulmonoscorpius", ja: "プルモノスコルピウス変種" },
  { en: "Purlovia", ja: "プルロヴィア" },
  { en: "Polar Purlovia", ja: "プルロヴィア (雪原)" },
  { en: "Aberrant Purlovia", ja: "プルロヴィア変種" },
  { en: "Plesiosaur", ja: "プレシオサウルス" },
  { en: "Procoptodon", ja: "プロコプトドン" },
  { en: "Brontosaurus", ja: "ブロントサウルス" },
  { en: "Dung Beetle", ja: "フンコロガシ" },
  { en: "Aberrant Dung Beetle", ja: "フンコロガシ変種" },
  { en: "Beta King Titan", ja: "ベータ・コロッサル・タイタン" },
  { en: "Beelzebufo", ja: "ベールゼブフォ" },
  { en: "Aberrant Beelzebufo", ja: "ベールゼブフォ変種" },
  { en: "Beyla", ja: "ベイラ" },
  { en: "Beyla Spawn", ja: "ベイラ・スポーン" },
  { en: "Pegomastax", ja: "ペゴマスタクス" },
  { en: "Hesperornis", ja: "ヘスペロルニス" },
  { en: "Pelagornis", ja: "ペラゴルニス" },
  { en: "Velonasaur", ja: "ベロナサウルス" },
  { en: "Poison Wyvern", ja: "ポイズンワイバーン" },
  { en: "Polar Bear", ja: "ホッキョクグマ" },
  { en: "Magmasaur", ja: "マグマサウルス" },
  { en: "Macro-Summoner", ja: "マクロ・サモナー" },
  { en: "Macrophage", ja: "マクロファージ" },
  { en: "Managarmr", ja: "マナガルム" },
  { en: "Manta", ja: "マンタ" },
  { en: "Aberrant Manta", ja: "マンタ変種" },
  { en: "Manticore", ja: "マンティコア" },
  { en: "Mammoth", ja: "マンモス" },
  { en: "Microraptor", ja: "ミクロラプトル" },
  { en: "Maewing", ja: "メイウィング" },
  { en: "Mega Mek", ja: "メガMEK" },
  { en: "Megachelon", ja: "メガケロン" },
  { en: "Megatherium", ja: "メガテリウム" },
  { en: "Meganeura", ja: "メガネウラ" },
  { en: "Aberrant Meganeura", ja: "メガネウラ変種" },
  { en: "Megapithecus", ja: "メガピテクス" },
  { en: "Piranha", ja: "メガピラニア" },
  { en: "Aberrant Piranha", ja: "メガピラニア変種" },
  { en: "Megalania", ja: "メガラニア" },
  { en: "Aberrant Megalania", ja: "メガラニア変種" },
  { en: "Megaloceros", ja: "メガロケロス" },
  { en: "Megalosaurus", ja: "メガロサウルス" },
  { en: "Aberrant Megalosaurus", ja: "メガロサウルス変種" },
  { en: "Megalodon", ja: "メガロドン" },
  { en: "Mesopithecus", ja: "メソピテクス" },
  { en: "Mosasaurus", ja: "モササウルス" },
  { en: "Moschops", ja: "モスコプス" },
  { en: "Aberrant Moschops", ja: "モスコプス変種" },
  { en: "Morellatops", ja: "モレラトプス" },
  { en: "Thorny Dragon", ja: "モロクトカゲ" },
  { en: "Lamprey", ja: "ヤツメウナギ" },
  { en: "Yutyrannus", ja: "ユウティラヌス" },
  { en: "Raptor", ja: "ユタラプトル" },
  { en: "Aberrant Raptor", ja: "ユタラプトル変種" },
  { en: "Unicorn", ja: "ユニコーン" },
  { en: "Lightning Wyvern", ja: "ライトニングワイバーン" },
  { en: "Lava Elemental", ja: "ラヴァエレメンタル" },
  { en: "Rubble Bear", ja: "ラブル・ベアー" },
  { en: "Rubble Golem", ja: "ラブルゴーレム" },
  { en: "Ravager", ja: "ラベジャー" },
  { en: "Leedsichthys", ja: "リードシクティス" },
  { en: "Reaper King", ja: "リーパーキング" },
  { en: "Reaper Queen", ja: "リーパークイーン" },
  { en: "Liopleurodon", ja: "リオプレウロドン" },
  { en: "Lystrosaurus", ja: "リストロサウルス" },
  { en: "Aberrant Lystrosaurus", ja: "リストロサウルス変種" },
  { en: "Lymantria", ja: "リマントリア" },
  { en: "Roll Rat", ja: "ロールラット" },
  { en: "Rockwell", ja: "ロックウェル" },
  { en: "Rockwell Node", ja: "ロックウェル・ノード" },
  { en: "Rockwell Prime", ja: "ロックウェル・プライム" },
  { en: "Rockwell Tentacle", ja: "ロックウェルの触手" },
  { en: "Rock Elemental", ja: "ロックエレメンタル" },
  { en: "Rock Drake", ja: "ロックドレイク" },
  { en: "Trilobite", ja: "三葉虫" },
  { en: "Aberrant Trilobite", ja: "三葉虫変種" },
  { en: "Brute X-Allosaurus", ja: "凶暴なXアロサウルス" },
  { en: "Brute X-Spino", ja: "凶暴なXスピノサウルス" },
  { en: "Brute X-Rex", ja: "凶暴なXティラノサウルス" },
  { en: "Brute X-Megalodon", ja: "凶暴なXメガロドン" },
  { en: "Brute X-Mosasaurus", ja: "凶暴なXモササウルス" },
  { en: "Brute X-Yutyrannus", ja: "凶暴なXユウティラヌス" },
  { en: "Brute X-Raptor", ja: "凶暴なXユタラプトル" },
  { en: "Brute X-Rock Elemental", ja: "凶暴なXロックエレメンタル" },
  { en: "Brute Astrocetus", ja: "凶暴なアストロセタス" },
  { en: "Brute Araneo", ja: "凶暴なアラネオモーフス" },
  { en: "Brute Sarco", ja: "凶暴なサルコスクス" },
  { en: "Brute Seeker", ja: "凶暴なシーカー" },
  { en: "Brute Tusoteuthis", ja: "凶暴なトゥソテウティス" },
  { en: "Brute Basilosaurus", ja: "凶暴なバシロサウルス" },
  { en: "Brute Fire Wyvern", ja: "凶暴なファイアワイバーン" },
  { en: "Brute Ferox", ja: "凶暴なフェロクス" },
  { en: "Brute Bloodstalker", ja: "凶暴なブラッドストーカー" },
  { en: "Brute Plesiosaur", ja: "凶暴なプレシオサウルス" },
  { en: "Brute Magmasaur", ja: "凶暴なマグマサウルス" },
  { en: "Brute Mammoth", ja: "凶暴なマンモス" },
  { en: "Brute Megaloceros", ja: "凶暴なメガロケロス" },
  { en: "Brute Leedsichthys", ja: "凶暴なリードシクティス" },
  { en: "Archaeopteryx", ja: "始祖鳥" },
  { en: "Eel Minion", ja: "子ウナギ (ミニオン)" },
  { en: "Experimental Giganotosaurus", ja: "実験体ギガノトサウルス" },
  { en: "Giant Bee", ja: "巨大ハチ" },
  { en: "Giant Queen Bee", ja: "巨大女王バチ" },
  { en: "Corrupted Arthropluera", ja: "汚染されたアースロプレウラ" },
  { en: "Corrupted Avatar", ja: "汚染されたアバター" },
  { en: "Corrupted Chalicotherium", ja: "汚染されたカリコテリウム" },
  { en: "Corrupted Carnotaurus", ja: "汚染されたカルノタウルス" },
  { en: "Corrupted Giganotosaurus", ja: "汚染されたギガノトサウルス" },
  { en: "Corrupted Survivor", ja: "汚染されたサバイバー" },
  { en: "Corrupted Stegosaurus", ja: "汚染されたステゴサウルス" },
  { en: "Corrupted Spino", ja: "汚染されたスピノサウルス" },
  { en: "Corrupted Dimorphodon", ja: "汚染されたディモルフォドン" },
  { en: "Corrupted Rex", ja: "汚染されたティラノサウルス" },
  { en: "Corrupted Dilophosaur", ja: "汚染されたディロフォサウルス" },
  { en: "Corrupted Deathworm", ja: "汚染されたデスワーム" },
  { en: "Corrupted Triceratops", ja: "汚染されたトリケラトプス" },
  { en: "Corrupted Paraceratherium", ja: "汚染されたパラケラテリウム" },
  { en: "Corrupted Pteranodon", ja: "汚染されたプテラノドン" },
  { en: "Corrupted Raptor", ja: "汚染されたユタラプトル" },
  { en: "Corrupted Reaper King", ja: "汚染されたリーパーキング" },
  { en: "Corrupted Rock Drake", ja: "汚染されたロックドレイク" },
  { en: "Corrupted Wyvern", ja: "汚染されたワイバーン" },
  { en: "Corrupted Master Controller", ja: "汚染された支配者" },
  { en: "Corrupt Tumor", ja: "汚染された腫瘍" },
  { en: "Moeder, Master of the Ocean", ja: "深海の女王・ムーダー" },
  { en: "Enraged Triceratops", ja: "激怒したトリケラトプス" },
  { en: "Enraged Corrupted Rex", ja: "激怒した汚染されたティラノサウルス" },
  { en: "Diseased Leech", ja: "病気持ちのヒル" },
  { en: "Overseer", ja: "監督者" },
  { en: "Insect Swarm", ja: "虫の大群" },
  { en: "Golden Striped Megalodon", ja: "金縞のメガロドン" },
  { en: "Golden Striped Brute Megalodon", ja: "金縞の凶暴なメガロドン" },
  { en: "Defense Unit", ja: "防御ユニット" },
  { en: "Snow Owl", ja: "雪フクロウ" },
] as const;
