/*
    このファイルは、検索に使用する名前一覧を生成するためのツールです。
    create-values で生成したSpecies と辞書から日本語名の紐づけを行います。
*/

import fs from "node:fs";
import { ALL_SPECIES } from "../src/asb/values/index.js";

function deleteDuplicate(list: typeof DICT) {
  const tmpList1 = Array.from(
    new Map(list.map((obj) => [obj.en, obj])).values(),
  );
  const tmpList2 = Array.from(
    new Map(tmpList1.map((obj) => [obj.ja, obj])).values(),
  );
  return tmpList2;
}

function getNames() {
  const valuesNames = ALL_SPECIES.map((s) => s.name).filter(
    (s) => s !== null && s !== undefined,
  );
  const safeDict = DICT.filter((d) => valuesNames.includes(d.en));
  return deleteDuplicate(safeDict).sort((a, b) => a.ja.localeCompare(b.ja));
}

/**
 * この関数は、いきものの名前の一覧を出力します。
 * @param outputPath 出力ファイルのパス
 */
function createConstTs(dict: typeof DICT, outputPath: string) {
  // values.ts の内容を作成
  const content = `
// このファイルは機械的に出力されました。

  export const NAME_DICT: {en:string,ja:string}[] = [\n  ${dict
    .map((d) => `{en:"${d.en}",ja:"${d.ja}"},`)
    .join("\n")
    .trim()}\n] as const;
    `;

  // ファイルを出力
  fs.writeFileSync(outputPath, content, "utf-8");
}

function main() {
  const dict = getNames();
  createConstTs(dict, "./src/asb/name-dict.ts");
}

const DICT: { en: string; ja: string }[] = [
  { en: "R-Allosaurus", ja: "Rアロサウルス" },
  { en: "R-Equus", ja: "Rエクウス" },
  { en: "R-Gasbags", ja: "Rガスバッグ" },
  { en: "R-Carnotaurus", ja: "Rカルノタウルス" },
  { en: "R-Carbonemys", ja: "Rカルボネミス" },
  { en: "R-Giganotosaurus", ja: "Rギガノトサウルス" },
  { en: "R-Quetzal", ja: "Rケツァルコアトルス" },
  { en: "R-Dire Bear", ja: "Rショートフェイスベア" },
  { en: "R-Direwolf", ja: "Rダイアウルフ" },
  { en: "R-Daeodon", ja: "Rダエオドン" },
  { en: "R-Thylacoleo", ja: "Rティラコレオ" },
  { en: "R-Dilophosaur", ja: "Rディロフォサウルス" },
  { en: "R-Parasaur", ja: "Rパラサウロロフス" },
  { en: "R-Procoptodon", ja: "Rプロコプトドン" },
  { en: "R-Brontosaurus", ja: "Rブロントサウルス" },
  { en: "R-Velonasaur", ja: "Rベロナサウルス" },
  { en: "R-Megatherium", ja: "Rメガテリウム" },
  { en: "R-Reaper King", ja: "Rリーパーキング" },
  { en: "R-Reaper Queen", ja: "Rリーパークイーン" },
  { en: "R-Snow Owl", ja: "R雪フクロウ" },
  { en: "Tek Quetzal", ja: "TEKケツァルコアトルス" },
  { en: "Tek Stegosaurus", ja: "TEKステゴサウルス" },
  { en: "Tek Stryder", ja: "TEKストライダー" },
  { en: "Tek Rex", ja: "TEKティラノサウルス" },
  { en: "Tek Triceratops", ja: "TEKトリケラトプス" },
  { en: "Tek Parasaur", ja: "TEKパラサウロロフス" },
  { en: "Tek Raptor", ja: "TEKユタラプトル" },
  { en: "Tek Giganotosaurus", ja: "TEKギガノトサウルス" },
  { en: "VR Arthropluera", ja: "VRアースロプレウラ" },
  { en: "VR Astrodelphis", ja: "VRアストロデルフィス" },
  { en: "VR Araneo", ja: "VRアラネオモーフス" },
  { en: "VR Argentavis", ja: "VRアルゲンタヴィス" },
  { en: "VR Allosaurus", ja: "VRアロサウルス" },
  { en: "VR Enforcer", ja: "VRエンフォーサー" },
  { en: "VR Onyc", ja: "VRオニコニクテリス" },
  { en: "VR Kaprosuchus", ja: "VRカプロスクス" },
  { en: "VR Mantis", ja: "VRカマキリ" },
  { en: "VR Chalicotherium", ja: "VRカリコテリウム" },
  { en: "VR Karkinos", ja: "VRカルキノス" },
  { en: "VR Carnotaurus", ja: "VRカルノタウルス" },
  { en: "VR Shadowmane", ja: "VRシャドウメイン" },
  { en: "VR Stegosaurus", ja: "VRステゴサウルス" },
  { en: "VR Tapejara", ja: "VRタペヤラ" },
  { en: "VR Titanoboa", ja: "VRティタノボア" },
  { en: "VR Dimorphodon", ja: "VRディモルフォドン" },
  { en: "VR Rex", ja: "VRティラノサウルス" },
  { en: "VR Dilophosaur", ja: "VRディロフォサウルス" },
  { en: "VR Terror Bird", ja: "VRテラーバード" },
  { en: "VR Triceratops", ja: "VRトリケラトプス" },
  { en: "VR Pachy", ja: "VRパキケファロサウルス" },
  { en: "VR Parasaur", ja: "VRパラサウロロフス" },
  { en: "VR Ferox", ja: "VRフェロクス" },
  { en: "VR Bloodstalker", ja: "VRブラッドストーカー" },
  { en: "VR Pulmonoscorpius", ja: "VRプルモノスコルピウス" },
  { en: "VR Velonasaur", ja: "VRベロナサウルス" },
  { en: "VR Megatherium", ja: "VRメガテリウム" },
  { en: "VR Megalania", ja: "VRメガラニア" },
  { en: "VR Raptor", ja: "VRユタラプトル" },
  { en: "VR Ravager", ja: "VRラベジャー" },
  { en: "VR Lymantria", ja: "VRリマントリア" },
  { en: "X-Argentavis", ja: "Xアルゲンタヴィス" },
  { en: "X-Allosaurus", ja: "Xアロサウルス" },
  { en: "X-Ankylosaurus", ja: "Xアンキロサウルス" },
  { en: "X-Ichthyosaurus", ja: "Xイクチオサウルス" },
  { en: "X-Otter", ja: "Xカワウソ" },
  { en: "X-Woolly Rhino", ja: "Xケブカサイ" },
  { en: "X-Sabertooth", ja: "Xサーベルタイガー" },
  { en: "X-Spino", ja: "Xスピノサウルス" },
  { en: "X-Sabertooth Salmon", ja: "Xセイバートゥース・サーモン" },
  { en: "X-Tapejara", ja: "Xタペヤラ" },
  { en: "X-Dunkleosteus", ja: "Xダンクルオステウス" },
  { en: "X-Rex", ja: "Xティラノサウルス" },
  { en: "X-Triceratops", ja: "Xトリケラトプス" },
  { en: "X-Basilosaurus", ja: "Xバシロサウルス" },
  { en: "X-Paraceratherium", ja: "Xパラケラテリウム" },
  { en: "X-Parasaur", ja: "Xパラサウロロフス" },
  { en: "X-Megalodon", ja: "Xメガロドン" },
  { en: "X-Mosasaurus", ja: "Xモササウルス" },
  { en: "X-Yutyrannus", ja: "Xユウティラヌス" },
  { en: "X-Raptor", ja: "Xユタラプトル" },
  { en: "X-Rock Elemental", ja: "Xロックエレメンタル" },
  { en: "Alpha X-Triceratops", ja: "アルファ・Xトリケラトプス" },
  { en: "Alpha Karkinos", ja: "アルファ・カルキノス" },
  { en: "Alpha Carno", ja: "アルファ・カルノタウルス" },
  { en: "Alpha Carnotaurus", ja: "アルファ・カルノタウルス" },
  {
    en: "Alpha Surface Reaper King",
    ja: "アルファ・サーフェス・リーパーキング",
  },
  { en: "Alpha Deathworm", ja: "アルファ・デスワーム" },
  { en: "Alpha Tusoteuthis", ja: "アルファ・トゥソテウティス" },
  { en: "Alpha Basilisk", ja: "アルファ・バジリスク" },
  { en: "Alpha Fire Wyvern", ja: "アルファ・ファイアワイバーン" },
  {
    en: "Alpha Blood Crystal Wyvern",
    ja: "アルファ・ブラッド・クリスタルワイバーン",
  },
  { en: "Alpha Megalodon", ja: "アルファ・メガロドン" },
  { en: "Alpha Mosasaur", ja: "アルファ・モササウルス" },
  { en: "Alpha Mosasaurus", ja: "アルファ・モササウルス" },
  { en: "Alpha Raptor", ja: "アルファ・ラプトル" },
  { en: "Alpha Leedsichthys", ja: "アルファ・リードシクティス" },
  { en: "Alpha T-Rex", ja: "アルファ・レックス" },
  { en: "Super Turkey", ja: "スーパー七面鳥" },
  { en: "Zomdodo", ja: "ゾンビドードー" },
  { en: "Zombie Fire Wyvern", ja: "ゾンビファイアワイバーン" },
  { en: "Zombie Poison Wyvern", ja: "ゾンビポイズンワイバーン" },
  { en: "Zombie Lightning Wyvern", ja: "ゾンビライトニングワイバーン" },
  { en: "Zombie Wyvern", ja: "ゾンビワイバーン" },
  { en: "Turkey", ja: "七面鳥" },
  { en: "Mantis Ghost", ja: "ゴーストカマキリ" },
  { en: "Surface Reaper King Ghost", ja: "ゴーストサーフェス・リーパーキング" },
  { en: "Direwolf Ghost", ja: "ゴーストダイアウルフ" },
  { en: "Rex Ghost", ja: "ゴーストティラノサウルス" },
  { en: "Basilisk Ghost", ja: "ゴーストバジリスク" },
  { en: "Bulbdog Ghost", ja: "ゴーストバルブドッグ" },
  { en: "Snow Owl Ghost", ja: "ゴースト雪フクロウ" },
  { en: "Skeletal Carnotaurus", ja: "スケルタル・カルノタウルス" },
  { en: "Skeletal Giganotosaurus", ja: "スケルタル・ギガノトサウルス" },
  { en: "Skeletal Quetzal", ja: "スケルタル・ケツァルコアトルス" },
  { en: "Skeletal Stego", ja: "スケルタル・ステゴサウルス" },
  { en: "Skeletal Rex", ja: "スケルタル・ティラノサウルス" },
  { en: "Skeletal Jerboa", ja: "スケルタル・トビネズミ" },
  { en: "Skeletal Trike", ja: "スケルタル・トリケラトプス" },
  {
    en: "Bone Fire Wyvern",
    ja: "ファイル:スケルタル・ファイアワイバーン.png スケルタル・ファイアワイバーン",
  },
  { en: "Skeletal Bronto", ja: "スケルタル・ブロントサウルス" },
  { en: "Skeletal Raptor", ja: "スケルタル・ユタラプトル" },
  { en: "Party Dodo", ja: "パーティードードー" },
  { en: "Bunny Dodo", ja: "バニードードー" },
  { en: "Malfunctioned Mek Knight", ja: "エラーを起こしたMEKナイト" },
  { en: "Malfunctioned Attack Drone", ja: "エラーを起こしたアタックドローン" },
  { en: "Malfunctioned Enforcer", ja: "エラーを起こしたエンフォーサー" },
  {
    en: "Brute Malfunctioned Tek Giganotosaurus",
    ja: "エラーを起こした凶暴なTEKギガノトサウルス",
  },
  {
    en: "Brute Malfunctioned Tek Rex",
    ja: "エラーを起こした凶暴なTEKティラノサウルス",
  },
  { en: "Malfunctioned Defense Unit", ja: "エラーを起こした防御ユニット" },
  { en: "Malfunctioned Tek Rex", ja: "エラーを起こしたTEKティラノサウルス" },
  {
    en: "Malfunctioned Tek Triceratops",
    ja: "エラーを起こしたTEKトリケラトプス",
  },
  { en: "Malfunctioned Tek Raptor", ja: "エラーを起こしたTEKユタラプトル" },
  {
    en: "Malfunctioned Tek Giganotosaurus",
    ja: "エラーを起こしたTEKギガノトサウルス",
  },
  {
    en: "Malfunctioned Tek Quetzal",
    ja: "エラーを起こしたTEKケツァルコアトルス",
  },
  {
    en: "Malfunctioned Tek Stegosaurus",
    ja: "エラーを起こしたTEKステゴサウルス",
  },
  {
    en: "Malfunctioned Tek Parasaur",
    ja: "エラーを起こしたTEKパラサウロロフス",
  },
  { en: "Malfunctioned Tek Stryder", ja: "エラーを起こしたTEKストライダー" },
  { en: "Corrupted Arthropluera", ja: "汚染されたアースロプレウラ" },
  { en: "Corrupted Chalicotherium", ja: "汚染されたカリコテリウム" },
  { en: "Corrupted Carnotaurus", ja: "汚染されたカルノタウルス" },
  { en: "Corrupted Giganotosaurus", ja: "汚染されたギガノトサウルス" },
  { en: "Corrupted Stegosaurus", ja: "汚染されたステゴサウルス" },
  { en: "Corrupted Spino", ja: "汚染されたスピノサウルス" },
  { en: "Corrupted Dimorphodon", ja: "汚染されたディモルフォドン" },
  { en: "Corrupted Rex", ja: "汚染されたティラノサウルス" },
  { en: "Corrupted Dilophosaur", ja: "汚染されたディロフォサウルス" },
  { en: "Corrupted Triceratops", ja: "汚染されたトリケラトプス" },
  { en: "Corrupted Paraceratherium", ja: "汚染されたパラケラテリウム" },
  { en: "Corrupted Pteranodon", ja: "汚染されたプテラノドン" },
  { en: "Corrupted Raptor", ja: "汚染されたユタラプトル" },
  { en: "Corrupted Reaper King", ja: "汚染されたリーパーキング" },
  { en: "Corrupted Rock Drake", ja: "汚染されたロックドレイク" },
  { en: "Corrupted Wyvern", ja: "汚染されたワイバーン" },
  { en: "Brute X-Allosaurus", ja: "凶暴なXアロサウルス" },
  { en: "Brute X-Spino", ja: "凶暴なXスピノサウルス" },
  { en: "Brute X-Rex", ja: "凶暴なXティラノサウルス" },
  { en: "Brute X-Megalodon", ja: "凶暴なXメガロドン" },
  { en: "Brute X-Mosasaurus", ja: "凶暴なXモササウルス" },
  { en: "Brute X-Yutyrannus", ja: "凶暴なXユウティラヌス" },
  { en: "Brute X-Rock Elemental", ja: "凶暴なXロックエレメンタル" },
  { en: "Brute Astrocetus", ja: "凶暴なアストロセタス" },
  { en: "Brute Araneo", ja: "凶暴なアラネオモーフス" },
  { en: "Brute Araneo", ja: "凶暴なアラネオモーフス" },
  { en: "Brute Sarco", ja: "凶暴なサルコスクス" },
  { en: "Brute Seeker", ja: "凶暴なシーカー" },
  { en: "Brute Tusoteuthis", ja: "凶暴なトゥソテウティス" },
  { en: "Brute Basilosaurus", ja: "凶暴なバシロサウルス" },
  { en: "Brute Fire Wyvern", ja: "凶暴なファイアワイバーン" },
  { en: "Brute Ferox", ja: "凶暴なフェロクス" },
  { en: "Brute Bloodstalker", ja: "凶暴なブラッドストーカー" },
  { en: "Brute Plesiosaur", ja: "凶暴なプレシオサウルス" },
  { en: "Brute Magmasaur", ja: "凶暴なマグマサウルス" },
  { en: "Brute Mammoth", ja: "凶暴なマンモス" },
  { en: "Brute Megaloceros", ja: "凶暴なメガロケロス" },
  { en: "Brute Leedsichthys", ja: "凶暴なリードシクティス" },
  { en: "Brute Reaper King", ja: "凶暴なリーパーキング" },
  { en: "Brute X-Raptor", ja: "凶暴なXユタラプトル" },
  { en: "Enraged Triceratops", ja: "激怒したトリケラトプス" },
  { en: "Enraged Corrupted Rex", ja: "激怒した汚染されたティラノサウルス" },
  { en: "Aberrant Arthropluera", ja: "アースロプレウラ変種" },
  { en: "Aberrant Achatina", ja: "アフリカマイマイ変種" },
  { en: "Aberrant Araneo", ja: "アラネオモーフス変種" },
  { en: "Aberrant Ankylosaurus", ja: "アンキロサウルス変種" },
  { en: "Aberrant Anglerfish", ja: "アンコウ変種" },
  { en: "Aberrant Iguanodon", ja: "イグアノドン変種" },
  { en: "Aberrant Equus", ja: "エクウス変種" },
  { en: "Aberrant Carnotaurus", ja: "カルノタウルス変種" },
  { en: "Aberrant Carbonemys", ja: "カルボネミス変種" },
  { en: "Aberrant Otter", ja: "カワウソ変種" },
  { en: "Aberrant Gigantopithecus", ja: "ギガントピテクス変種" },
  { en: "Aberrant Cnidaria", ja: "クニダリア変種" },
  { en: "Aberrant Salmon", ja: "サーモン変種" },
  { en: "Aberrant Sarco", ja: "サルコスクス変種" },
  { en: "Abberant Coelacanth", ja: "シーラカンス変種" },
  { en: "Aberrant Coelacanth", ja: "シーラカンス変種" },
  { en: "Aberrant Dire Bear", ja: "ショートフェイスベア変種" },
  { en: "Aberrant Stegosaurus", ja: "ステゴサウルス変種" },
  { en: "Aberrant Spino", ja: "スピノサウルス変種" },
  { en: "Aberrant Sabertooth Salmon", ja: "セイバートゥース・サーモン変種" },
  { en: "Aberrant Titanoboa", ja: "ティタノボア変種" },
  { en: "Aberrant Diplocaulus", ja: "ディプロカウルス変種" },
  { en: "Aberrant Diplodocus", ja: "ディプロドクス変種" },
  { en: "Aberrant Dimetrodon", ja: "ディメトロドン変種" },
  { en: "Aberrant Dimorphodon", ja: "ディモルフォドン変種" },
  { en: "Aberrant Electrophorus", ja: "デンキウナギ変種" },
  { en: "Aberrant Doedicurus", ja: "ドエディクルス変種" },
  { en: "Aberrant Dodo", ja: "ドードー変種" },
  { en: "Aberrant Triceratops", ja: "トリケラトプス変種" },
  { en: "Aberrant Paraceratherium", ja: "パラケラテリウム変種" },
  { en: "Aberrant Parasaur", ja: "パラサウロロフス変種" },
  { en: "Aberrant Baryonyx", ja: "バリオニクス変種" },
  { en: "Aberrant Ovis", ja: "ヒツジ変種" },
  { en: "Aberrant Pulmonoscorpius", ja: "プルモノスコルピウス変種" },
  { en: "Aberrant Purlovia", ja: "プルロヴィア変種" },
  { en: "Aberrant Dung Beetle", ja: "フンコロガシ変種" },
  { en: "Aberrant Beelzebufo", ja: "ベールゼブフォ変種" },
  { en: "Aberrant Manta", ja: "マンタ変種" },
  { en: "Aberrant Meganeura", ja: "メガネウラ変種" },
  { en: "Aberrant Piranha", ja: "メガピラニア変種" },
  { en: "Aberrant Megalania", ja: "メガラニア変種" },
  { en: "Aberrant Megalosaurus", ja: "メガロサウルス変種" },
  { en: "Aberrant Moschops", ja: "モスコプス変種" },
  { en: "Aberrant Raptor", ja: "ユタラプトル変種" },
  { en: "Aberrant Lystrosaurus", ja: "リストロサウルス変種" },
  { en: "Aberrant Trilobite", ja: "三葉虫変種" },
  { en: "Fenrisúlfr", ja: "フェンリル (ボス)" },
  { en: "Broodmother", ja: "ブルードマザー" },
  { en: "Broodmother Lysrix", ja: "ブルードマザー" },
  { en: "Manticore", ja: "マンティコア" },
  { en: "Megapithecus", ja: "メガピテクス" },
  { en: "Rockwell", ja: "ロックウェル" },
  { en: "Rockwell Prime", ja: "ロックウェル・プライム" },
  { en: "Corrupted Master Controller", ja: "汚染された支配者" },
  { en: "Overseer", ja: "監督者" },
  { en: "Moeder, Master of the Ocean", ja: "深海の女王・ムーダー" },
  { en: "Dragon", ja: "ドラゴン" },
  { en: "Dinopithecus King", ja: "ディノピテクスキング" },
  { en: "Crystal Wyvern Queen", ja: "クリスタルワイバーンクイーン" },
  {
    en: "ファイル:Broodmother Guardian.png Broodmother Guardian",
    ja: "ファイル:Broodmother Guardian.png Broodmother Guardian",
  },
  { en: "Dragon Guardian", ja: "Dragon Guardian" },
  {
    en: "ファイル:Megapithecus Guardian.png Megapithecus Guardian",
    ja: "ファイル:Megapithecus Guardian.png Megapithecus Guardian",
  },
  { en: "King Titan", ja: "コロッサル・タイタン" },
  { en: "Rockwell Node", ja: "ロックウェル・ノード" },
  { en: "Alpha King Titan", ja: "アルファ・コロッサル・タイタン" },
  { en: "Gamma King Titan", ja: "ガンマ・コロッサル・タイタン" },
  { en: "Beta King Titan", ja: "ベータ・コロッサル・タイタン" },
  {
    en: "Crystal Wyvern Queen (Alpha)",
    ja: "クリスタルワイバーンクイーン(アルファ)",
  },
  {
    en: "Crystal Wyvern Queen (Gamma)",
    ja: "クリスタルワイバーンクイーン(ガンマ)",
  },
  {
    en: "Crystal Wyvern Queen (Beta)",
    ja: "クリスタルワイバーンクイーン(ベータ)",
  },
  { en: "Fenrisúlfr (Alpha)", ja: "フェンリル(アルファ)" },
  { en: "Fenrisúlfr (Beta)", ja: "フェンリル(ベータ)" },
  { en: "Fenrisúlfr (Gamma)", ja: "フェンリル(ガンマ)" },
  { en: "Dragon (Alpha)", ja: "ドラゴン(アルファ)" },
  { en: "Dragon (Gamma)", ja: "ドラゴン(ガンマ)" },
  { en: "Dragon (Beta)", ja: "ドラゴン(ベータ)" },
  { en: "Dinopithecus King (Alpha)", ja: "ディノピテクスキング(アルファ)" },
  { en: "Dinopithecus King (Beta)", ja: "ディノピテクスキング(ベータ)" },
  { en: "Dinopithecus King (Gamma)", ja: "ディノピテクスキング(ガンマ)" },
  { en: "Broodmother Lysrix (Alpha)", ja: "ブルードマザー(アルファ)" },
  { en: "Broodmother Lysrix (Gamma)", ja: "ブルードマザー(ガンマ)" },
  { en: "Broodmother Lysrix (Beta)", ja: "ブルードマザー(ベータ)" },
  { en: "Manticore (Alpha)", ja: "マンティコア(アルファ)" },
  { en: "Manticore (Gamma)", ja: "マンティコア(ガンマ)" },
  { en: "Manticore (Beta)", ja: "マンティコア(ベータ)" },
  { en: "Megapithecus (Alpha)", ja: "メガピテクス(アルファ)" },
  { en: "Megapithecus (Gamma)", ja: "メガピテクス(ガンマ)" },
  { en: "Megapithecus (Beta)", ja: "メガピテクス(ベータ)" },
  { en: "Rockwell (Alpha)", ja: "ロックウェル(アルファ)" },
  { en: "Rockwell (Gamma)", ja: "ロックウェル(ガンマ)" },
  { en: "Rockwell (Beta)", ja: "ロックウェル(ベータ)" },
  { en: "Rockwell Prime (Alpha)", ja: "ロックウェル・プライム(アルファ)" },
  { en: "Rockwell Prime (Gamma)", ja: "ロックウェル・プライム(ガンマ)" },
  { en: "Rockwell Prime (Beta)", ja: "ロックウェル・プライム(ベータ)" },
  { en: "Alpha Corrupted Master Controller", ja: "汚染された支配者(アルファ)" },
  { en: "Gamma Corrupted Master Controller", ja: "汚染された支配者(ガンマ)" },
  { en: "Beta Corrupted Master Controller", ja: "汚染された支配者(ベータ)" },
  { en: "Overseer (Alpha)", ja: "監督者(アルファ)" },
  { en: "Overseer (Gamma)", ja: "監督者(ガンマ)" },
  { en: "Overseer (Beta)", ja: "監督者(ベータ)" },
  {
    en: "Alpha Moeder, Master of the Ocean",
    ja: "深海の女王・ムーダー(アルファ)",
  },
  {
    en: "Gamma Moeder, Master of the Ocean",
    ja: "深海の女王・ムーダー(ガンマ)",
  },
  {
    en: "Beta Moeder, Master of the Ocean",
    ja: "深海の女王・ムーダー(ベータ)",
  },
  { en: "Bosses", ja: "ボス" },
  { en: "Corrupted Creatures", ja: "汚染された生物" },
  { en: "Enraged Creatures", ja: "激怒した生物" },
  {
    en: "ファイル:Rockwell Prime Tentacle.png Rockwell Prime Tentacle",
    ja: "ロックウェル・プライムの触手",
  },
  { en: "Rockwell Tentacle", ja: "ロックウェルの触手" },
  { en: "RockwellTentacle (Alpha)", ja: "ロックウェルの触手(アルファ)" },
  { en: "RockwellTentacle (Gamma)", ja: "ロックウェルの触手(ガンマ)" },
  { en: "RockwellTentacle (Beta)", ja: "ロックウェルの触手(ベータ)" },
  { en: "Eel Minion", ja: "子ウナギ (ミニオン)" },
  { en: "Defense Unit", ja: "防御ユニット" },
  {
    en: "ファイル:Deathworm (Minion).png Deathworm (Minion)",
    ja: "デスワーム (ミニオン)",
  },
  { en: "Argentustus", ja: "Argentustus (ARK: Survival Evolved Mobile)" },
  { en: "Beelzemorbus", ja: "Beelzemorbus (ARK: Survival Evolved Mobile)" },
  { en: "Broodgenetrix", ja: "Broodgenetrix (ARK: Survival Evolved Mobile)" },
  { en: "Cubozoa Multis", ja: "Cubozoa Multis (ARK: Survival Evolved Mobile)" },
  {
    en: "Doedicurus Vastus",
    ja: "Doedicurus Vastus (ARK: Survival Evolved Mobile)",
  },
  { en: "Gula Beetle", ja: "Gula Beetle (ARK: Survival Evolved Mobile)" },
  {
    en: "Megapithecus Pestis",
    ja: "Megapithecus Pestis (ARK: Survival Evolved Mobile)",
  },
  { en: "Noctis", ja: "Noctis (ARK: Survival Evolved Mobile)" },
  { en: "Obsidioequus", ja: "Obsidioequus (ARK: Survival Evolved Mobile)" },
  { en: "Royal Griffin", ja: "Royal Griffin (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Achatina", ja: "Eerie Achatina (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Allosaurus",
    ja: "Eerie Allosaurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Alpha Carno",
    ja: "Eerie Alpha Carno (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Alpha Mosasaur",
    ja: "Eerie Alpha Mosasaur (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Alpha Raptor",
    ja: "Eerie Alpha Raptor (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Alpha T-Rex",
    ja: "Eerie Alpha T-Rex (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Ammonite", ja: "Eerie Ammonite (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Angler", ja: "Eerie Angler (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Ankylo", ja: "Eerie Ankylo (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Araneo", ja: "Eerie Araneo (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Archaeopteryx",
    ja: "Eerie Archaeopteryx (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Argentavis",
    ja: "Eerie Argentavis (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Arthropluera",
    ja: "Eerie Arthropluera (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Baryonyx", ja: "Eerie Baryonyx (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Basilosaurus",
    ja: "Eerie Basilosaurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Beelzebufo",
    ja: "Eerie Beelzebufo (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Bronto", ja: "Eerie Bronto (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Carbonemys",
    ja: "Eerie Carbonemys (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Carno", ja: "Eerie Carno (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Castoroides",
    ja: "Eerie Castoroides (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Chalicotherium",
    ja: "Eerie Chalicotherium (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Coelacanth",
    ja: "Eerie Coelacanth (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Compy", ja: "Eerie Compy (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Daeodon", ja: "Eerie Daeodon (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Dilophosaurus",
    ja: "Eerie Dilophosaurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Dimetrodon",
    ja: "Eerie Dimetrodon (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Dimorphodon",
    ja: "Eerie Dimorphodon (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Diplocaulus",
    ja: "Eerie Diplocaulus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Diplodocus",
    ja: "Eerie Diplodocus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Dire Bear",
    ja: "Eerie Dire Bear (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Dire Wolf",
    ja: "Eerie Dire Wolf (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Dodo", ja: "Eerie Dodo (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Doedicurus",
    ja: "Eerie Doedicurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Dung Beetle",
    ja: "Eerie Dung Beetle (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Dunkleosteus",
    ja: "Eerie Dunkleosteus (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Equus", ja: "Eerie Equus (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Eurypterid",
    ja: "Eerie Eurypterid (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Gallimimus",
    ja: "Eerie Gallimimus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Giganotosaurus",
    ja: "Eerie Giganotosaurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Gigantopithecus",
    ja: "Eerie Gigantopithecus (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Griffin", ja: "Eerie Griffin (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Ichthyosaurus",
    ja: "Eerie Ichthyosaurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Iguanodon",
    ja: "Eerie Iguanodon (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Jerboa", ja: "Eerie Jerboa (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Kairuku", ja: "Eerie Kairuku (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Kaprosuchus",
    ja: "Eerie Kaprosuchus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "ファイル:Eerie Leech (Diseased).png Eerie Leech (Diseased)",
    ja: "ファイル:Mobile Eerie Leech (Diseased).png Eerie Leech (Diseased) (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Leedsichthys",
    ja: "Eerie Leedsichthys (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Liopleurodon",
    ja: "Eerie Liopleurodon (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Lystrosaurus",
    ja: "Eerie Lystrosaurus (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Mammoth", ja: "Eerie Mammoth (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Manta", ja: "Eerie Manta (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Megaloceros",
    ja: "Eerie Megaloceros (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Megalodon",
    ja: "Eerie Megalodon (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Megalosaurus",
    ja: "Eerie Megalosaurus (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Meganeura",
    ja: "Eerie Meganeura (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Megapiranha",
    ja: "Eerie Megapiranha (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Megatherium",
    ja: "Eerie Megatherium (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Mesopithecus",
    ja: "Eerie Mesopithecus (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Mosasaur", ja: "Eerie Mosasaur (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Moschops", ja: "Eerie Moschops (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Onyc", ja: "Eerie Onyc (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Otter", ja: "Eerie Otter (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Oviraptor",
    ja: "Eerie Oviraptor (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Pachy", ja: "Eerie Pachy (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Pachyrhinosaurus",
    ja: "Eerie Pachyrhinosaurus (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Parasaur", ja: "Eerie Parasaur (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Pegomastax",
    ja: "Eerie Pegomastax (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Pelagornis",
    ja: "Eerie Pelagornis (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Phiomia", ja: "Eerie Phiomia (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Plesiosaur",
    ja: "Eerie Plesiosaur (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Procoptodon",
    ja: "Eerie Procoptodon (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Pteranodon",
    ja: "Eerie Pteranodon (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Pulmonoscorpius",
    ja: "Eerie Pulmonoscorpius (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Purlovia", ja: "Eerie Purlovia (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Quetzal", ja: "Eerie Quetzal (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Raptor", ja: "Eerie Raptor (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Rex", ja: "Eerie Rex (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Sabertooth",
    ja: "Eerie Sabertooth (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Sabertooth Salmon",
    ja: "Eerie Sabertooth Salmon (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Sarco", ja: "Eerie Sarco (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Spino", ja: "Eerie Spino (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Stego", ja: "Eerie Stego (ARK: Survival Evolved Mobile)" },
  { en: "Eerie Tapejara", ja: "Eerie Tapejara (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Terror Bird",
    ja: "Eerie Terror Bird (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Therizinosaur",
    ja: "Eerie Therizinosaur (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Titanoboa",
    ja: "Eerie Titanoboa (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Titanomyrma Drone",
    ja: "Eerie Titanomyrma Drone (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Titanomyrma Soldier",
    ja: "Eerie Titanomyrma Soldier (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Titanosaur",
    ja: "Eerie Titanosaur (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Triceratops",
    ja: "Eerie Triceratops (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Trilobite",
    ja: "Eerie Trilobite (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Troodon", ja: "Eerie Troodon (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Tusoteuthis",
    ja: "Eerie Tusoteuthis (ARK: Survival Evolved Mobile)",
  },
  {
    en: "Eerie Woolly Rhinoceros",
    ja: "Eerie Woolly Rhinoceros (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Yeti", ja: "Eerie Yeti (ARK: Survival Evolved Mobile)" },
  {
    en: "Eerie Diseased Leech",
    ja: "Eerie Diseased Leech (ARK: Survival Evolved Mobile)",
  },
  { en: "Eerie Leech", ja: "Eerie Leech (ARK: Survival Evolved Mobile)" },
  { en: "Corrupted Avatar", ja: "汚染されたアバター" },
  { en: "Corrupted Survivor", ja: "汚染されたサバイバー" },
  { en: "Corrupt Tumor", ja: "汚染された腫瘍" },
  { en: "Corrupted Deathworm", ja: "汚染されたデスワーム" },
  { en: "Attack Drone", ja: "アタックドローン" },
  { en: "Exo-Mek", ja: "エクソMEK" },
  { en: "Mek", ja: "MEK" },
  { en: "Giant Worker Bee", ja: "Giant Worker Bee" },
  { en: "Arthropluera", ja: "アースロプレウラ" },
  { en: "Ice Titan", ja: "アイス・タイタン" },
  { en: "Ice Golem", ja: "アイスエレメンタル" },
  { en: "Iceworm Male", ja: "アイスワーム(オス)" },
  { en: "Iceworm Queen", ja: "アイスワーム(女王)" },
  {
    en: "ファイル:Iceworm Queen Arena.png Iceworm Queen Arena",
    ja: "ファイル:アイスワーム(女王) (アリーナ).png アイスワーム(女王) (アリーナ)",
  },
  { en: "Ice Wyvern", ja: "アイスワイバーン" },
  { en: "Astrocetus", ja: "アストロセタス" },
  { en: "Astrodelphis", ja: "アストロデルフィス" },
  { en: "Achatina", ja: "アフリカマイマイ" },
  { en: "Amargasaurus", ja: "アマルガサウルス" },
  { en: "Araneo", ja: "アラネオモーフス" },
  { en: "Spider", ja: "アラネオモーフス" },
  { en: "Argentavis", ja: "アルゲンタヴィス" },
  { en: "Allosaurus", ja: "アロサウルス" },
  { en: "Ankylo", ja: "アンキロサウルス" },
  { en: "Ankylosaurus", ja: "アンキロサウルス" },
  { en: "Angler", ja: "アンコウ" },
  { en: "Anglerfish", ja: "アンコウ" },
  { en: "Andrewsarchus", ja: "アンドリューサルクス" },
  { en: "Ammonite", ja: "アンモナイト" },
  { en: "Yeti", ja: "イエティ" },
  { en: "Iguanodon", ja: "イグアノドン" },
  { en: "Ichthy", ja: "イクチオサウルス" },
  { en: "Ichthyosaurus", ja: "イクチオサウルス" },
  { en: "Ichthyornis", ja: "イクチオルニス" },
  { en: "Voidwyrm", ja: "ヴォイドワーム" },
  { en: "Eurypterid", ja: "ウミサソリ" },
  { en: "Equus", ja: "エクウス" },
  { en: "Elemental Reaper King", ja: "エレメンタル・リーパーキング" },
  { en: "Ember Crystal Wyvern", ja: "エンバー・クリスタルワイバーン" },
  { en: "Enforcer", ja: "エンフォーサー" },
  { en: "Oviraptor", ja: "オヴィラプトル" },
  { en: "Onyc", ja: "オニコニクテリス" },
  { en: "Onychonycteris", ja: "オニコニクテリス" },
  { en: "Kairuku", ja: "カイルクペンギン" },
  { en: "Castoroides", ja: "カストロイデス" },
  { en: "Gasbag", ja: "ガスバッグ" },
  { en: "Gasbags", ja: "ガスバッグ" },
  { en: "Gacha", ja: "ガチャ" },
  { en: "GachaClaus", ja: "ガチャクロース" },
  { en: "Kaprosuchus", ja: "カプロスクス" },
  { en: "Mantis", ja: "カマキリ" },
  { en: "Chalicotherium", ja: "カリコテリウム" },
  { en: "Gallimimus", ja: "ガリミムス" },
  {
    en: "ファイル:Carcharodonto.png Carcharodonto",
    ja: "カルカロドントサウルス",
  },
  { en: "Carcharodontosaurus", ja: "カルカロドントサウルス" },
  { en: "Karkinos", ja: "カルキノス" },
  { en: "Carno", ja: "カルノタウルス" },
  { en: "Carnotaurus", ja: "カルノタウルス" },
  { en: "Carbonemys", ja: "カルボネミス" },
  { en: "Otter", ja: "カワウソ" },
  { en: "Giganotosaurus", ja: "ギガノトサウルス" },
  { en: "Gigantopithecus", ja: "ギガントピテクス" },
  { en: "Cnidaria", ja: "クニダリア" },
  { en: "Crystal Wyvern", ja: "クリスタルワイバーン" },
  { en: "Griffin", ja: "グリフィン" },
  { en: "Glowtail", ja: "グローテール" },
  { en: "Glowbug", ja: "グローバグ" },
  { en: "Quetzal", ja: "ケツァルコアトルス" },
  { en: "Quetzalcoatlus", ja: "ケツァルコアトルス" },
  { en: "Woolly Rhino", ja: "ケブカサイ" },
  { en: "Woolly Rhinoceros", ja: "ケブカサイ" },
  { en: "Kentrosaurus", ja: "ケントロサウルス" },
  { en: "Compsognathus", ja: "コンプソグナトゥス" },
  { en: "Compy", ja: "コンプソグナトゥス" },
  {
    en: "ファイル:Surface Seeker.png Surface Seeker",
    ja: "ファイル:サーフェス・シーカー.png サーフェス・シーカー",
  },
  { en: "Surface Reaper King", ja: "サーフェス・リーパーキング" },
  { en: "Sabertooth", ja: "サーベルタイガー" },
  { en: "Smilodon", ja: "サーベルタイガー" },
  { en: "Subterranean Reaper King", ja: "サブテラニアン・リーパーキング" },
  { en: "Summoner", ja: "サモナー" },
  { en: "Sarco", ja: "サルコスクス" },
  { en: "Sarcosuchus", ja: "サルコスクス" },
  { en: "Seeker", ja: "シーカー" },
  { en: "Coelacanth", ja: "シーラカンス" },
  { en: "Sinomacrops", ja: "シノマクロプス" },
  { en: "Shinehorn", ja: "シャインホーン" },
  { en: "Jug Bug", ja: "ジャグ・バグ" },
  { en: "Oil Jug Bug", ja: "ジャグ・バグ(原油)" },
  { en: "Water Jug Bug", ja: "ファイル:ジャグバグ(水).png ジャグバグ(水)" },
  { en: "Shadowmane", ja: "シャドウメイン" },
  { en: "Dire Bear", ja: "ショートフェイスベア" },
  { en: "Scout", ja: "スカウト" },
  { en: "Sköll", ja: "スコル" },
  { en: "Steinbjörn", ja: "スタインヨルン" },
  { en: "Stygimoloch", ja: "スティギモロク" },
  { en: "Styracosaurus", ja: "スティラコサウルス" },
  { en: "Stegosaurus", ja: "ステゴサウルス" },
  { en: "Spino", ja: "スピノサウルス" },
  { en: "Spirit Dire Bear", ja: "スピリット・ショートフェイスベア" },
  { en: "Spirit Direbear", ja: "スピリット・ショートフェイスベア" },
  { en: "Spirit Direwolf", ja: "スピリット・ダイアウルフ" },
  { en: "Sabertooth Salmon", ja: "セイバートゥース・サーモン" },
  { en: "Direwolf", ja: "ダイアウルフ" },
  { en: "Dire Polar Bear", ja: "ダイアホッキョクグマ" },
  { en: "Titans", ja: "タイタン" },
  { en: "Daeodon", ja: "ダエオドン" },
  { en: "Tapejara", ja: "タペヤラ" },
  { en: "ファイル:Dunkle.png Dunkle", ja: "ダンクルオステウス" },
  { en: "Dunkleosteus", ja: "ダンクルオステウス" },
  { en: "Chalk Golem", ja: "チョークエレメンタル" },
  { en: "Titanosaur", ja: "ティタノサウルス" },
  { en: "Titanoboa", ja: "ティタノボア" },
  { en: "Titanomyrma", ja: "ティタノミルマ" },
  { en: "Titanomyrma Soldier", ja: "ティタノミルマ・ソルジャー" },
  { en: "Titanomyrma Drone", ja: "ティタノミルマ・ドローン" },
  { en: "Deinonychus", ja: "デイノニクス" },
  { en: "Dinopithecus", ja: "ディノピテクス" },
  { en: "Diplocaulus", ja: "ディプロカウルス" },
  { en: "Diplodocus", ja: "ディプロドクス" },
  { en: "Dimetrodon", ja: "ディメトロドン" },
  { en: "Dimorphodon", ja: "ディモルフォドン" },
  { en: "Thylacoleo", ja: "ティラコレオ" },
  { en: "Rex", ja: "ティラノサウルス" },
  { en: "Tyrannosaurus Rex", ja: "ティラノサウルス" },
  { en: "Dilo", ja: "ディロフォサウルス" },
  { en: "Dilophosaur", ja: "ディロフォサウルス" },
  { en: "Desert Titan", ja: "デザート・タイタン" },
  { en: "Desert Titan Flock", ja: "デザート・タイタンの群れ" },
  { en: "Desmodus", ja: "デスモダス" },
  { en: "Deathworm", ja: "デスワーム" },
  { en: "Terror Bird", ja: "テラーバード" },
  { en: "Therizinosaur", ja: "テリジノサウルス" },
  { en: "Therizinosaurus", ja: "テリジノサウルス" },
  { en: "Electrophorus", ja: "デンキウナギ" },
  { en: "Tusoteuthis", ja: "トゥソテウティス" },
  { en: "Doedicurus", ja: "ドエディクルス" },
  { en: "Dodo", ja: "ドードー" },
  { en: "DodoRex", ja: "ドードーレックス" },
  { en: "Dodo Wyvern", ja: "ドードーワイバーン" },
  { en: "Jerboa", ja: "トビネズミ" },
  { en: "Triceratops", ja: "トリケラトプス" },
  { en: "Trike", ja: "トリケラトプス" },
  { en: "Troodon", ja: "トロオドン" },
  { en: "Tropical Crystal Wyvern", ja: "トロピカル・クリスタルワイバーン" },
  { en: "Tropeognathus", ja: "トロペオグナトゥス" },
  { en: "Human (Male)", ja: "人間 (男)" },
  { en: "Human (Female)", ja: "人間 (女)" },
  { en: "Nameless", ja: "ネームレス" },
  { en: "Noglin", ja: "ノグリン" },
  { en: "Pachy", ja: "パキケファロサウルス" },
  { en: "Pachycephalosaurus", ja: "パキケファロサウルス" },
  { en: "Pachyrhino", ja: "パキリノサウルス" },
  { en: "Pachyrhinosaurus", ja: "パキリノサウルス" },
  { en: "Vulture", ja: "ハゲワシ" },
  { en: "Basilisk", ja: "バジリスク" },
  { en: "Basilosaurus", ja: "バシロサウルス" },
  { en: "Hati", ja: "ハティ" },
  { en: "Hati and Sköll", ja: "ハティとスコル" },
  { en: "Bunny Oviraptor", ja: "バニーオヴィラプトル" },
  { en: "Parakeet Fish School", ja: "パラキートの魚群" },
  { en: "Paracer", ja: "パラケラテリウム" },
  { en: "Paraceratherium", ja: "パラケラテリウム" },
  { en: "Parasaur", ja: "パラサウロロフス" },
  { en: "Parasaurolophus", ja: "パラサウロロフス" },
  { en: "Baryonyx", ja: "バリオニクス" },
  { en: "Bulbdog", ja: "バルブドッグ" },
  { en: "Hyaenodon", ja: "ヒエノドン" },
  { en: "Ovis", ja: "ヒツジ" },
  { en: "Leech", ja: "ヒル" },
  { en: "Fire Wyvern", ja: "ファイアワイバーン" },
  { en: "Phiomia", ja: "フィオミア" },
  { en: "Fjordhawk", ja: "フィヨルドホーク" },
  { en: "Featherlight", ja: "フェザーライト" },
  { en: "Phoenix", ja: "フェニックス" },
  { en: "Ferox", ja: "フェロクス" },
  { en: "Ferox (Large)", ja: "フェロクス (大)" },
  { en: "Fenrir", ja: "フェンリル" },
  { en: "Forest Titan", ja: "フォレスト・タイタン" },
  { en: "Forest Wyvern", ja: "フォレストワイバーン" },
  { en: "Pteranodon", ja: "プテラノドン" },
  { en: "Blood Crystal Wyvern", ja: "ブラッド・クリスタルワイバーン" },
  { en: "Bloodstalker", ja: "ブラッドストーカー" },
  { en: "Pulmonoscorpius", ja: "プルモノスコルピウス" },
  { en: "Scorpion", ja: "プルモノスコルピウス" },
  { en: "Purlovia", ja: "プルロヴィア" },
  { en: "Polar Purlovia", ja: "プルロヴィア (雪原)" },
  { en: "Plesiosaur", ja: "プレシオサウルス" },
  { en: "Procoptodon", ja: "プロコプトドン" },
  { en: "Bronto", ja: "ブロントサウルス" },
  { en: "Brontosaurus", ja: "ブロントサウルス" },
  { en: "Dung Beetle", ja: "フンコロガシ" },
  { en: "Beyla", ja: "ベイラ" },
  { en: "Beyla Spawn", ja: "ベイラ・スポーン" },
  { en: "Beelzebufo", ja: "ベールゼブフォ" },
  { en: "Pegomastax", ja: "ペゴマスタクス" },
  { en: "Hesperornis", ja: "ヘスペロルニス" },
  { en: "Pelagornis", ja: "ペラゴルニス" },
  { en: "Velonasaur", ja: "ベロナサウルス" },
  { en: "Poison Wyvern", ja: "ポイズンワイバーン" },
  { en: "Polar Bear", ja: "ホッキョクグマ" },
  { en: "Magmasaur", ja: "マグマサウルス" },
  { en: "Macro-Summoner", ja: "マクロ・サモナー" },
  { en: "Macrophage", ja: "マクロファージ" },
  { en: "Managarmr", ja: "マナガルム" },
  { en: "Manta", ja: "マンタ" },
  { en: "Mammoth", ja: "マンモス" },
  { en: "Microraptor", ja: "ミクロラプトル" },
  { en: "Insect Swarm", ja: "虫の大群" },
  { en: "Maewing", ja: "メイウィング" },
  { en: "Mega Mek", ja: "メガMEK" },
  { en: "Megachelon", ja: "メガケロン" },
  { en: "Megatherium", ja: "メガテリウム" },
  { en: "Meganeura", ja: "メガネウラ" },
  { en: "Megapiranha", ja: "メガピラニア" },
  { en: "Piranha", ja: "メガピラニア" },
  { en: "Megalania", ja: "メガラニア" },
  { en: "Megaloceros", ja: "メガロケロス" },
  { en: "Megalosaurus", ja: "メガロサウルス" },
  { en: "Megalodon", ja: "メガロドン" },
  { en: "Mesopithecus", ja: "メソピテクス" },
  { en: "Mosasaurus", ja: "モササウルス" },
  { en: "Moschops", ja: "モスコプス" },
  { en: "ファイル:Camelsaurus.png Camelsaurus", ja: "モレラトプス" },
  { en: "Morellatops", ja: "モレラトプス" },
  { en: "Thorny Dragon", ja: "モロクトカゲ" },
  { en: "Lamprey", ja: "ヤツメウナギ" },
  { en: "Yutyrannus", ja: "ユウティラヌス" },
  { en: "Raptor", ja: "ユタラプトル" },
  { en: "Utahraptor", ja: "ユタラプトル" },
  { en: "Unicorn", ja: "ユニコーン" },
  { en: "Lightning Wyvern", ja: "ライトニングワイバーン" },
  { en: "Lava Elemental", ja: "ラヴァエレメンタル" },
  { en: "Raptor Claus", ja: "ラプトルクロース" },
  { en: "Rubble Bear", ja: "ラブル・ベアー" },
  { en: "Rubble Golem", ja: "ラブルゴーレム" },
  { en: "Ravager", ja: "ラベジャー" },
  { en: "Leedsichthys", ja: "リードシクティス" },
  { en: "Reaper", ja: "リーパー" },
  { en: "Reaper King", ja: "リーパーキング" },
  { en: "Reaper Queen", ja: "リーパークイーン" },
  { en: "Reaper Prince", ja: "リーパープリンス" },
  { en: "Liopleurodon", ja: "リオプレウロドン" },
  { en: "Lystrosaurus", ja: "リストロサウルス" },
  { en: "Lymantria", ja: "リマントリア" },
  { en: "Rare X-Sabertooth Salmon", ja: "レアXセイバートゥース・サーモン" },
  { en: "Roll Rat", ja: "ロールラット" },
  { en: "Rock Elemental", ja: "ロックエレメンタル" },
  { en: "Rock Drake", ja: "ロックドレイク" },
  { en: "Wyvern", ja: "ワイバーン" },
  { en: "Giant Queen Bee", ja: "巨大女王バチ" },
  { en: "Giant Bee", ja: "巨大ハチ" },
  { en: "Golden Striped Megalodon", ja: "金縞のメガロドン" },
  { en: "Golden Striped Brute Megalodon", ja: "金縞の凶暴なメガロドン" },
  { en: "Trilobite", ja: "三葉虫" },
  { en: "Archaeopteryx", ja: "始祖鳥" },
  { en: "Experimental Giganotosaurus", ja: "実験体ギガノトサウルス" },
  { en: "Human", ja: "人間" },
  { en: "Snow Owl", ja: "雪フクロウ" },
  { en: "Diseased Leech", ja: "病気持ちのヒル" },
  { en: "Injured Brute Reaper King", ja: "負傷した凶暴なリーパーキング" },
];

main();
