/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Privacy_policyRouteImport } from './routes/privacy_policy'
import { Route as Calc_valueRouteImport } from './routes/calc_value'
import { Route as Calc_levelRouteImport } from './routes/calc_level'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const Privacy_policyRoute = Privacy_policyRouteImport.update({
  id: '/privacy_policy',
  path: '/privacy_policy',
  getParentRoute: () => rootRouteImport,
} as any)
const Calc_valueRoute = Calc_valueRouteImport.update({
  id: '/calc_value',
  path: '/calc_value',
  getParentRoute: () => rootRouteImport,
} as any)
const Calc_levelRoute = Calc_levelRouteImport.update({
  id: '/calc_level',
  path: '/calc_level',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calc_level': typeof Calc_levelRoute
  '/calc_value': typeof Calc_valueRoute
  '/privacy_policy': typeof Privacy_policyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calc_level': typeof Calc_levelRoute
  '/calc_value': typeof Calc_valueRoute
  '/privacy_policy': typeof Privacy_policyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calc_level': typeof Calc_levelRoute
  '/calc_value': typeof Calc_valueRoute
  '/privacy_policy': typeof Privacy_policyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/calc_level' | '/calc_value' | '/privacy_policy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/calc_level' | '/calc_value' | '/privacy_policy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calc_level'
    | '/calc_value'
    | '/privacy_policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Calc_levelRoute: typeof Calc_levelRoute
  Calc_valueRoute: typeof Calc_valueRoute
  Privacy_policyRoute: typeof Privacy_policyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy_policy': {
      id: '/privacy_policy'
      path: '/privacy_policy'
      fullPath: '/privacy_policy'
      preLoaderRoute: typeof Privacy_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc_value': {
      id: '/calc_value'
      path: '/calc_value'
      fullPath: '/calc_value'
      preLoaderRoute: typeof Calc_valueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc_level': {
      id: '/calc_level'
      path: '/calc_level'
      fullPath: '/calc_level'
      preLoaderRoute: typeof Calc_levelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Calc_levelRoute: Calc_levelRoute,
  Calc_valueRoute: Calc_valueRoute,
  Privacy_policyRoute: Privacy_policyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
